import Namaste from "@truckmitr/src/app/layouts/auth/namaste"
import Welcome from "@truckmitr/src/app/layouts/auth/welcome"
import Login from "@truckmitr/src/app/layouts/auth/login"
import Signup from "@truckmitr/src/app/layouts/auth/signup"
import Otp from "@truckmitr/src/app/layouts/auth/otp"
import Language from "@truckmitr/src/app/layouts/auth/language"
import Approval from "@truckmitr/src/app/layouts/auth/approval"
import IntroVideo from "@truckmitr/src/app/layouts/auth/introVideo"
import ProfileCompletion from "@truckmitr/src/app/layouts/auth/profile-completion"
import ProfileCompletionForeman from "@truckmitr/src/app/layouts/auth/foreman-profile-completion"
import Congratulations from "@truckmitr/src/app/layouts/auth/congratulations"
import ModuleSelection from "@truckmitr/src/app/layouts/auth/moduleSelection"
import ModuleSelectionNew from "@truckmitr/src/app/layouts/auth/moduleSelection/ModuleSelectionNew"

export { Namaste, Welcome, Login, Signup, Otp, Language, Approval, IntroVideo, ProfileCompletion, ProfileCompletionForeman, Congratulations, ModuleSelection, ModuleSelectionNew }